/*    ____         ________     __      _        ______  
 *   |  _ \_      |  ______|   |  \    | |     _/  ____\
 *   | | \_ \_    |  |         |   \   | |    /  _/   
 *   | |   \  |   |  |_____    | |\ \  | |   |  |   _____ 
 *   | |    | |   |  ______|   | | \ \ | |   |  |  |___  | 
 *   | |  _/ _|   |  |         | |  \ \| |    \  \    / /
 *   | |_/ _/     |  |_____    | |   \   |     \_ \__/ /
 *   |____/       |________|   |_|    \__|       \____/
 *               
 * __________________________________________________________
 * __________________________________________________________
 *                       Project DENG 
 *
 *
 * Copyright (C) 2020 - 2021
 * This Software is licensed under Apache License as described 
 * in the LICENSE.md file, which you should have recieved with 
 * this distribution.
 * 
 * You may reproduce and distribute copies of the
 * Work or Derivative Works thereof in any medium, with or without
 * modifications, and in Source or Object form, provided that You
 * meet the following conditions:
 *
 * (a) You must give any other recipients of the Work or
 *     Derivative Works a copy of this License; and
 *
 * (b) You must cause any modified files to carry prominent notices
 *     stating that You changed the files; and
 *
 * (c) You must retain, in the Source form of any Derivative Works
 *     that You distribute, all copyright, patent, trademark, and
 *     attribution notices from the Source form of the Work,
 *     excluding those notices that do not pertain to any part of
 *     the Derivative Works; and
 *
 * (d) If the Work includes a "NOTICE" text file as part of its
 *     distribution, then any Derivative Works that You distribute must
 *     include a readable copy of the attribution notices contained
 *     within such NOTICE file, excluding those notices that do not
 *     pertain to any part of the Derivative Works, in at least one
 *     of the following places: within a NOTICE text file distributed
 *     as part of the Derivative Works; within the Source form or
 *     documentation, if provided along with the Derivative Works; or,
 *     within a display generated by the Derivative Works, if and
 *     wherever such third-party notices normally appear. The contents
 *     of the NOTICE file are for informational purposes only and
 *     do not modify the License. You may add Your own attribution
 *     notices within Derivative Works that You distribute, alongside
 *     or as an addendum to the NOTICE text from the Work, provided
 *     that such additional attribution notices cannot be construed
 *     as modifying the License.
 *
 * You may add Your own copyright statement to Your modifications and
 * may provide additional or different license terms and conditions
 * for use, reproduction, or distribution of Your modifications, or
 * for any such Derivative Works as a whole, provided Your use,
 * reproduction, and distribution of the Work otherwise complies with
 * the conditions stated in this License.
 */ 


#define __VK_EXT_C
#include <vk_ext.h>

void neko_GetRequiredVKSurfaceExt(
    neko_SurfaceWindow *p_win,
    char ***p_exts,
    uint32_t *p_ext_c, 
    bool add_layer_ext
) {
    if(add_layer_ext) {
        *p_ext_c = 3;
        *p_exts = (char**) malloc((*p_ext_c) * sizeof(char*));
        (*p_exts)[2] = calloc(32, sizeof(char));
        strcpy((*p_exts)[2], NEKO_VK_DEBUG_UTILS_EXT_NAME);
    }

    else {
        *p_ext_c = 2;
        (*p_exts) = (char**) malloc((*p_ext_c) * sizeof(char*));
    }

    **p_exts = (char*) calloc(32, sizeof(char));
    strcpy(**p_exts, NEKO_VK_WSI_EXT_NAME);

    #if defined(__linux__)
        *(*p_exts + 1) = (char*) calloc(32, sizeof(char));
        strcpy(*(*p_exts + 1), NEKO_VK_XLIB_SURFACE_EXT_NAME);

    #elif defined(_WIN32)
        *(*p_exts + 1) = (char*) calloc(32, sizeof(char));
        strcpy(*(*p_exts + 1), NEKO_VK_WIN32_SURFACE_EXT_NAME);
    #endif
}


VkResult neko_InitVKSurface (
    neko_SurfaceWindow *p_win, 
    VkInstance *p_instance, 
    VkSurfaceKHR *p_surface
) {
    #ifdef __linux__
        VkXlibSurfaceCreateInfoKHR surface_info;
        surface_info.sType = VK_STRUCTURE_TYPE_XLIB_SURFACE_CREATE_INFO_KHR;
        surface_info.window = p_win->x11_handler.window;
        surface_info.dpy = p_win->x11_handler.p_display;
        surface_info.flags = 0;
        surface_info.pNext = NULL;

        PFN_vkCreateXlibSurfaceKHR vkCreateXlibSurfaceKHR;
        vkCreateXlibSurfaceKHR = (PFN_vkCreateXlibSurfaceKHR) vkGetInstanceProcAddr(*p_instance, "vkCreateXlibSurfaceKHR");

        return vkCreateXlibSurfaceKHR(*p_instance, &surface_info, NULL, p_surface);
    #endif

    #ifdef _WIN32
        VkWin32SurfaceCreateInfoKHR surface_info;
        surface_info.sType = VK_STRUCTURE_TYPE_WIN32_SURFACE_CREATE_INFO_KHR;
        surface_info.hinstance = p_win->win32_handler.win.hInstance;
        surface_info.hwnd = p_win->win32_handler.hwnd;
        surface_info.pNext = NULL;
        
        PFN_vkCreateWin32SurfaceKHR vkCreateWin32SurfaceKHR;
        vkCreateWin32SurfaceKHR = (PFN_vkCreateWin32SurfaceKHR) vkGetInstanceProcAddr(*p_instance, "vkCreateWin32SurfaceKHR");

        return vkCreateWin32SurfaceKHR(*p_instance, &surface_info, NULL, p_surface);
    #endif

    return VK_ERROR_UNKNOWN;
} 
